export default [
    'click',
    'dblclick',
    'mousedown',
    'mouseup',
    'mousemove',
    // 'mouseout',
    'dragstart',
    'drag',
    'dragenter',
    'dragleave',
    'dragover',
    'drop',
    'dragend',
    'keydown',
    'keypress',
    'keyup',
    'load',
    'unload',
    'abort',
    'error',
    'resize',
    'scroll',
    'select',
    'change',
    'submit',
    'reset',
    'focus',
    // 'blur',
    'focusin',
    // 'focusout',
    // 'DOMActivate',
    // 'DOMSubtreeModified',
    // 'DOMNodeInserted',
    // 'DOMNodeRemoved',
    // 'DOMNodeRemovedFromDocument',
    // 'DOMNodeInsertedIntoDocument',
    // 'DOMAttrModified',
    // 'DOMCharacterDataModified',
    'loadstart',
    'progress',
    'error',
    'abort',
    'load',
    'loadend'
];
